<a href="https://colab.research.google.com/github/Aryan2079/Data-Science-Training/blob/main/Day_11_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([1,5,25,8,3,56])


In [4]:
np.sort(a)

array([ 1,  3,  5,  8, 25, 56])

In [5]:
arr = np.array([1,2,3])
demoArr = np.array([2,4,6,7,8])
np.concatenate((arr,demoArr))

array([1, 2, 3, 2, 4, 6, 7, 8])

In [6]:
array_example = np.array([[0,1,2,3],[4,5,6,7],[4,5,6,7]])

In [7]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [8]:
array_example.shape

(3, 4)

In [10]:
array_example.ndim

2

In [11]:
array_example.size

12

## Reshape

In [12]:
demo_array = np.arange(10)
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
practice_arr = np.arange(64)
practice_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [15]:
practice_arr.reshape(16,4)
practice_arr.reshape(4,4,4)
practice_arr.reshape(8,2,4)
# practice_arr.reshape(10,2)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [16]:
data = np.array([1,2,3])

In [17]:
data[1]

2

In [18]:
data[0:2]

array([1, 2])

In [20]:
data = np.array([[3,6,5],[7,8,4]])

In [21]:
data[1,2]

4

In [22]:
data[-1,-1]

4

In [23]:
data[data<5]

array([3, 4])

In [24]:
data[data>=6]

array([6, 7, 8])

In [25]:
five_up = (data>=5)
data[five_up]

array([6, 5, 7, 8])

In [26]:
div_array = np.arange(1,51)
div_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [27]:
query = (div_array%2==0)
div_array[query]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [29]:
li = [5,6,7,8]
list(map(lambda x:x*2,li))

[10, 12, 14, 16]

In [32]:
list_ = np.array([5,6,8,9])
list_*2

array([10, 12, 16, 18])

## Trignometry

In [33]:
a = np.array([5,6,7,1.5708])


In [34]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  1.        ])

In [35]:
np.cos(a)

array([ 2.83662185e-01,  9.60170287e-01,  7.53902254e-01, -3.67320510e-06])

In [36]:
np.tan(a)

array([-3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -2.72241808e+05])

In [39]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[4,5],[6,7]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [6 7]]


In [40]:
a = np.random.randn(2,3)
b = np.random.randn(3,2)
print(a)
print(b)

[[-0.70217281 -0.13874898  0.79360651]
 [-1.29376884 -0.94201314  0.62107244]]
[[-1.56103353 -0.09810023]
 [ 0.95067706  0.61110125]
 [-0.25775008 -0.44806743]]


In [41]:
np.matmul(a,b)

array([[ 0.7596577 , -0.37149559],
       [ 0.96398479, -0.72702872]])

In [42]:
rand_mat1 = np.random.randn(1000,3)
rand_mat2 = np.random.randn(3,1000)
np.matmul(rand_mat1, rand_mat2).shape

(1000, 1000)

Numpy Exercises
Multiply the following two NumPy arrays element-wise: [1, 2, 3] and [4, 5, 6], and print the result.
Calculate the mean of the following NumPy array: [3, 7, 10, 15, 19], and print the result.
Reshape the following NumPy array into a 2x3 matrix: [1, 2, 3, 4, 5, 6].
Find the maximum value in the following NumPy array: [9, 2, 7, 5, 3], and print it.
More exercises

Create a 2D NumPy array with shape (5, 5) containing random integers between 1 and 100. Replace all values greater than 50 with 0 and print the modified array.

Create a 1D NumPy array with 20 elements ranging from 0 to 100. Reshape the array into a 4x5 matrix and print it.

Create a 3x3 matrix with random values between 0 and 1. Replace all values less than 0.5 with 0 and print the modified matrix.

Create a 1D NumPy array with 100 elements ranging from 1 to 100. Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the sum.

Create a 2D NumPy array with shape (4, 4) containing random integers between 1 and 10. Find the indices of the maximum value in each row and print the indices.

Create a 1D NumPy array with 50 random elements randomly. Calculate the mean and standard deviation of the array and print the results.

Create a 2D NumPy array with shape (3, 3) and fill it with values ranging from 0 to 8. Shuffle the rows randomly and print the shuffled array.

Create a 1D NumPy array with 100 elements ranging from 1 to 10. Replace all odd values with -1 and print the modified array.

Create a 3x3 matrix with random values between 0 and 1. Normalize the matrix by dividing each row by the sum of its elements and print the normalized matrix.

Create a 2D NumPy array with shape (5, 5) and fill it with random values between 0 and 1. Sort the elements in each column in descending order and print the sorted array.

In [43]:
matA=[1,2,3]
matB=[4,5,6]
np.multiply(matA,matB)

array([ 4, 10, 18])

In [44]:
mean_mat = [3, 7, 10, 15, 19]
np.mean(mean_mat)

10.8

In [45]:
reshape_mat = [1, 2, 3, 4, 5, 6]
np.reshape(reshape_mat,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
max_mat = [9, 2, 7, 5, 3]
np.max(max_mat)

9

In [49]:
modify_mat = np.random.randint(1,100,(5,5))
modify_mat

array([[15, 63,  1,  5, 58],
       [21, 12, 18,  5, 84],
       [80,  3, 16, 27, 27],
       [66,  7, 49, 11, 82],
       [ 5, 78, 58, 71, 71]])

In [51]:
modify_mat[modify_mat>50]=0
modify_mat

array([[15,  0,  1,  5,  0],
       [21, 12, 18,  5,  0],
       [ 0,  3, 16, 27, 27],
       [ 0,  7, 49, 11,  0],
       [ 5,  0,  0,  0,  0]])

In [56]:
rand_arr = np.random.randint(1,100,20)
rand_arr

array([72, 55, 63, 46, 88, 17, 32, 81, 75, 49, 72, 76, 61, 83, 90, 54, 86,
       26, 92, 19])

In [57]:
rand_arr = np.reshape(rand_arr,(4,5))
rand_arr

array([[72, 55, 63, 46, 88],
       [17, 32, 81, 75, 49],
       [72, 76, 61, 83, 90],
       [54, 86, 26, 92, 19]])

In [71]:
rand_mat = np.random.randint(0,1,(3,3))
rand_mat[rand_mat<0.5]=0
rand_mat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
sum_mat = np.arange(1,101).reshape(10,10)
sum_mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
sum_mat.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [74]:
ran_arr = np.random.randint(1,10,(4,4))
ran_arr

array([[3, 1, 4, 4],
       [9, 8, 6, 4],
       [1, 8, 4, 2],
       [1, 6, 3, 7]])

In [75]:
rand_arr.argmax(axis=1)

array([], dtype=int64)